Header               header

int16[]              sensors
FromMotorDataType    motor_data_type
int16                which_motors
int32                which_motor_data_arrived
int32                which_motor_data_had_errors
int16[]              motor_data_packet_torque
int16[]              motor_data_packet_misc
int32                tactile_data_type
int16                tactile_data_valid
int16[]              tactile
int16                idle_time_us
