float64 position_p
float64 position_i
float64 position_d
float64 position_i_clamp
float64 min_velocity
float64 max_velocity
float64 position_deadband

float64 velocity_p
float64 velocity_i
float64 velocity_d
float64 velocity_i_clamp
float64 max_force

int32 friction_deadband
---
