# takes a vector of 5 doubles as the force thresholds
# with which a contact is detected.
# the order is FF; MF; RF; LF; TH

float64[] force_thresholds
---
float64[] touch_forces

# returns a vector of 5 touch forces, containing
# 0 if force < force_threshold, current force
# otherwise